//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proektirovanie_
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Гот товар.
    /// </summary>
    // *** Start programmer edit section *** (ГотТовар CustomAttributes)

    // *** End programmer edit section *** (ГотТовар CustomAttributes)
    [AutoAltered()]
    [Caption("Гот товар")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГотТоварE", new string[] {
            "Товар as \'Товар\'",
            "КолВо as \'Кол во\'",
            "Одобрено as \'Одобрено\'"})]
    public class ГотТовар : ICSSoft.STORMNET.DataObject
    {
        
        private string fТовар;
        
        private int fКолВо;
        
        private bool fОдобрено;
        
        private IIS.Proektirovanie_.Номенклатура fНоменклатура;
        
        // *** Start programmer edit section *** (ГотТовар CustomMembers)

        // *** End programmer edit section *** (ГотТовар CustomMembers)

        
        /// <summary>
        /// КолВо.
        /// </summary>
        // *** Start programmer edit section *** (ГотТовар.КолВо CustomAttributes)

        // *** End programmer edit section *** (ГотТовар.КолВо CustomAttributes)
        public virtual int КолВо
        {
            get
            {
                // *** Start programmer edit section *** (ГотТовар.КолВо Get start)

                // *** End programmer edit section *** (ГотТовар.КолВо Get start)
                int result = this.fКолВо;
                // *** Start programmer edit section *** (ГотТовар.КолВо Get end)

                // *** End programmer edit section *** (ГотТовар.КолВо Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГотТовар.КолВо Set start)

                // *** End programmer edit section *** (ГотТовар.КолВо Set start)
                this.fКолВо = value;
                // *** Start programmer edit section *** (ГотТовар.КолВо Set end)

                // *** End programmer edit section *** (ГотТовар.КолВо Set end)
            }
        }
        
        /// <summary>
        /// Одобрено.
        /// </summary>
        // *** Start programmer edit section *** (ГотТовар.Одобрено CustomAttributes)

        // *** End programmer edit section *** (ГотТовар.Одобрено CustomAttributes)
        public virtual bool Одобрено
        {
            get
            {
                // *** Start programmer edit section *** (ГотТовар.Одобрено Get start)

                // *** End programmer edit section *** (ГотТовар.Одобрено Get start)
                bool result = this.fОдобрено;
                // *** Start programmer edit section *** (ГотТовар.Одобрено Get end)

                // *** End programmer edit section *** (ГотТовар.Одобрено Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГотТовар.Одобрено Set start)

                // *** End programmer edit section *** (ГотТовар.Одобрено Set start)
                this.fОдобрено = value;
                // *** Start programmer edit section *** (ГотТовар.Одобрено Set end)

                // *** End programmer edit section *** (ГотТовар.Одобрено Set end)
            }
        }
        
        /// <summary>
        /// Товар.
        /// </summary>
        // *** Start programmer edit section *** (ГотТовар.Товар CustomAttributes)

        // *** End programmer edit section *** (ГотТовар.Товар CustomAttributes)
        [StrLen(255)]
        public virtual string Товар
        {
            get
            {
                // *** Start programmer edit section *** (ГотТовар.Товар Get start)

                // *** End programmer edit section *** (ГотТовар.Товар Get start)
                string result = this.fТовар;
                // *** Start programmer edit section *** (ГотТовар.Товар Get end)

                // *** End programmer edit section *** (ГотТовар.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГотТовар.Товар Set start)

                // *** End programmer edit section *** (ГотТовар.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (ГотТовар.Товар Set end)

                // *** End programmer edit section *** (ГотТовар.Товар Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Proektirovanie_.Номенклатура.
        /// </summary>
        // *** Start programmer edit section *** (ГотТовар.Номенклатура CustomAttributes)

        // *** End programmer edit section *** (ГотТовар.Номенклатура CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Номенклатура"})]
        public virtual IIS.Proektirovanie_.Номенклатура Номенклатура
        {
            get
            {
                // *** Start programmer edit section *** (ГотТовар.Номенклатура Get start)

                // *** End programmer edit section *** (ГотТовар.Номенклатура Get start)
                IIS.Proektirovanie_.Номенклатура result = this.fНоменклатура;
                // *** Start programmer edit section *** (ГотТовар.Номенклатура Get end)

                // *** End programmer edit section *** (ГотТовар.Номенклатура Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГотТовар.Номенклатура Set start)

                // *** End programmer edit section *** (ГотТовар.Номенклатура Set start)
                this.fНоменклатура = value;
                // *** Start programmer edit section *** (ГотТовар.Номенклатура Set end)

                // *** End programmer edit section *** (ГотТовар.Номенклатура Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГотТоварE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГотТоварE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГотТоварE", typeof(IIS.Proektirovanie_.ГотТовар));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ГотТовар.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfГотТовар CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfГотТовар CustomAttributes)
    public class DetailArrayOfГотТовар : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Proektirovanie_.DetailArrayOfГотТовар members)

        // *** End programmer edit section *** (IIS.Proektirovanie_.DetailArrayOfГотТовар members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ГотТовар by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ГотТовар.
        /// </summary>
        public DetailArrayOfГотТовар(IIS.Proektirovanie_.Номенклатура fНоменклатура) : 
                base(typeof(ГотТовар), ((ICSSoft.STORMNET.DataObject)(fНоменклатура)))
        {
        }
        
        public IIS.Proektirovanie_.ГотТовар this[int index]
        {
            get
            {
                return ((IIS.Proektirovanie_.ГотТовар)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Proektirovanie_.ГотТовар dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
