//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proektirovanie_
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Продажи.
    /// </summary>
    // *** Start programmer edit section *** (Продажи CustomAttributes)

    // *** End programmer edit section *** (Продажи CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПродажиE", new string[] {
            "Сотрудник as \'Сотрудник\'",
            "Клиент as \'Клиент\'",
            "Товар as \'Товар\'",
            "Цена as \'Цена\'",
            "КолВо as \'Кол во\'",
            "Сумма as \'Сумма\'",
            "Номенклатура as \'Номенклатура\'",
            "Номенклатура.ИмяТовара as \'Имя товара\'",
            "Клиент as \'Клиент\'",
            "Клиент.ФИО as \'ФИО\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Номенклатура.ИмяТовара",
            "Клиент.ФИО",
            "Сотрудник.ФИО"})]
    [MasterViewDefineAttribute("ПродажиE", "Номенклатура", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ИмяТовара")]
    [MasterViewDefineAttribute("ПродажиE", "Клиент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ПродажиE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ПродажиL", new string[] {
            "Сотрудник as \'Сотрудник\'",
            "Клиент as \'Клиент\'",
            "Товар as \'Товар\'",
            "Цена as \'Цена\'",
            "КолВо as \'Кол во\'",
            "Сумма as \'Сумма\'",
            "Номенклатура.ИмяТовара as \'Имя товара\'",
            "Клиент.ФИО as \'ФИО\'",
            "Сотрудник.ФИО as \'ФИО\'"})]
    public class Продажи : ICSSoft.STORMNET.DataObject
    {
        
        private string fОтветственный;
        
        private string fПокупатель;
        
        private string fТовар;
        
        private int fЦена;
        
        private int fКолВо;
        
        private int fСумма;
        
        private IIS.Proektirovanie_.Номенклатура fНоменклатура;
        
        private IIS.Proektirovanie_.Клиент fКлиент;
        
        private IIS.Proektirovanie_.Сотрудник fСотрудник;
        
        // *** Start programmer edit section *** (Продажи CustomMembers)

        // *** End programmer edit section *** (Продажи CustomMembers)

        
        /// <summary>
        /// КолВо.
        /// </summary>
        // *** Start programmer edit section *** (Продажи.КолВо CustomAttributes)

        // *** End programmer edit section *** (Продажи.КолВо CustomAttributes)
        public virtual int КолВо
        {
            get
            {
                // *** Start programmer edit section *** (Продажи.КолВо Get start)

                // *** End programmer edit section *** (Продажи.КолВо Get start)
                int result = this.fКолВо;
                // *** Start programmer edit section *** (Продажи.КолВо Get end)

                // *** End programmer edit section *** (Продажи.КолВо Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Продажи.КолВо Set start)

                // *** End programmer edit section *** (Продажи.КолВо Set start)
                this.fКолВо = value;
                // *** Start programmer edit section *** (Продажи.КолВо Set end)

                // *** End programmer edit section *** (Продажи.КолВо Set end)
            }
        }
        
        /// <summary>
        /// Ответственный.
        /// </summary>
        // *** Start programmer edit section *** (Продажи.Ответственный CustomAttributes)

        // *** End programmer edit section *** (Продажи.Ответственный CustomAttributes)
        [StrLen(255)]
        public virtual string Ответственный
        {
            get
            {
                // *** Start programmer edit section *** (Продажи.Ответственный Get start)

                // *** End programmer edit section *** (Продажи.Ответственный Get start)
                string result = this.fОтветственный;
                // *** Start programmer edit section *** (Продажи.Ответственный Get end)

                // *** End programmer edit section *** (Продажи.Ответственный Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Продажи.Ответственный Set start)

                // *** End programmer edit section *** (Продажи.Ответственный Set start)
                this.fОтветственный = value;
                // *** Start programmer edit section *** (Продажи.Ответственный Set end)

                // *** End programmer edit section *** (Продажи.Ответственный Set end)
            }
        }
        
        /// <summary>
        /// Покупатель.
        /// </summary>
        // *** Start programmer edit section *** (Продажи.Покупатель CustomAttributes)

        // *** End programmer edit section *** (Продажи.Покупатель CustomAttributes)
        [StrLen(255)]
        public virtual string Покупатель
        {
            get
            {
                // *** Start programmer edit section *** (Продажи.Покупатель Get start)

                // *** End programmer edit section *** (Продажи.Покупатель Get start)
                string result = this.fПокупатель;
                // *** Start programmer edit section *** (Продажи.Покупатель Get end)

                // *** End programmer edit section *** (Продажи.Покупатель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Продажи.Покупатель Set start)

                // *** End programmer edit section *** (Продажи.Покупатель Set start)
                this.fПокупатель = value;
                // *** Start programmer edit section *** (Продажи.Покупатель Set end)

                // *** End programmer edit section *** (Продажи.Покупатель Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Продажи.Сумма CustomAttributes)

        // *** End programmer edit section *** (Продажи.Сумма CustomAttributes)
        public virtual int Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Продажи.Сумма Get start)

                // *** End programmer edit section *** (Продажи.Сумма Get start)
                int result = this.fСумма;
                // *** Start programmer edit section *** (Продажи.Сумма Get end)

                // *** End programmer edit section *** (Продажи.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Продажи.Сумма Set start)

                // *** End programmer edit section *** (Продажи.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (Продажи.Сумма Set end)

                // *** End programmer edit section *** (Продажи.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Товар.
        /// </summary>
        // *** Start programmer edit section *** (Продажи.Товар CustomAttributes)

        // *** End programmer edit section *** (Продажи.Товар CustomAttributes)
        [StrLen(255)]
        public virtual string Товар
        {
            get
            {
                // *** Start programmer edit section *** (Продажи.Товар Get start)

                // *** End programmer edit section *** (Продажи.Товар Get start)
                string result = this.fТовар;
                // *** Start programmer edit section *** (Продажи.Товар Get end)

                // *** End programmer edit section *** (Продажи.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Продажи.Товар Set start)

                // *** End programmer edit section *** (Продажи.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (Продажи.Товар Set end)

                // *** End programmer edit section *** (Продажи.Товар Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Продажи.Цена CustomAttributes)

        // *** End programmer edit section *** (Продажи.Цена CustomAttributes)
        public virtual int Цена
        {
            get
            {
                // *** Start programmer edit section *** (Продажи.Цена Get start)

                // *** End programmer edit section *** (Продажи.Цена Get start)
                int result = this.fЦена;
                // *** Start programmer edit section *** (Продажи.Цена Get end)

                // *** End programmer edit section *** (Продажи.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Продажи.Цена Set start)

                // *** End programmer edit section *** (Продажи.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (Продажи.Цена Set end)

                // *** End programmer edit section *** (Продажи.Цена Set end)
            }
        }
        
        /// <summary>
        /// Продажи.
        /// </summary>
        // *** Start programmer edit section *** (Продажи.Клиент CustomAttributes)

        // *** End programmer edit section *** (Продажи.Клиент CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент"})]
        [NotNull()]
        public virtual IIS.Proektirovanie_.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (Продажи.Клиент Get start)

                // *** End programmer edit section *** (Продажи.Клиент Get start)
                IIS.Proektirovanie_.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (Продажи.Клиент Get end)

                // *** End programmer edit section *** (Продажи.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Продажи.Клиент Set start)

                // *** End programmer edit section *** (Продажи.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (Продажи.Клиент Set end)

                // *** End programmer edit section *** (Продажи.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Продажи.
        /// </summary>
        // *** Start programmer edit section *** (Продажи.Номенклатура CustomAttributes)

        // *** End programmer edit section *** (Продажи.Номенклатура CustomAttributes)
        [PropertyStorage(new string[] {
                "Номенклатура"})]
        [NotNull()]
        public virtual IIS.Proektirovanie_.Номенклатура Номенклатура
        {
            get
            {
                // *** Start programmer edit section *** (Продажи.Номенклатура Get start)

                // *** End programmer edit section *** (Продажи.Номенклатура Get start)
                IIS.Proektirovanie_.Номенклатура result = this.fНоменклатура;
                // *** Start programmer edit section *** (Продажи.Номенклатура Get end)

                // *** End programmer edit section *** (Продажи.Номенклатура Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Продажи.Номенклатура Set start)

                // *** End programmer edit section *** (Продажи.Номенклатура Set start)
                this.fНоменклатура = value;
                // *** Start programmer edit section *** (Продажи.Номенклатура Set end)

                // *** End programmer edit section *** (Продажи.Номенклатура Set end)
            }
        }
        
        /// <summary>
        /// Продажи.
        /// </summary>
        // *** Start programmer edit section *** (Продажи.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Продажи.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Proektirovanie_.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Продажи.Сотрудник Get start)

                // *** End programmer edit section *** (Продажи.Сотрудник Get start)
                IIS.Proektirovanie_.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Продажи.Сотрудник Get end)

                // *** End programmer edit section *** (Продажи.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Продажи.Сотрудник Set start)

                // *** End programmer edit section *** (Продажи.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Продажи.Сотрудник Set end)

                // *** End programmer edit section *** (Продажи.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПродажиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПродажиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПродажиE", typeof(IIS.Proektirovanie_.Продажи));
                }
            }
            
            /// <summary>
            /// "ПродажиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПродажиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПродажиL", typeof(IIS.Proektirovanie_.Продажи));
                }
            }
        }
    }
}
