//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proektirovanie_
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудник.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудник CustomAttributes)

    // *** End programmer edit section *** (Сотрудник CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникE", new string[] {
            "ФИО as \'ФИО\'",
            "Должность as \'Должность\'",
            "Отдел as \'Отдел\'",
            "Оклад as \'Оклад\'",
            "Тел as \'Тел\'"})]
    [View("СотрудникL", new string[] {
            "ФИО as \'ФИО\'",
            "Должность as \'Должность\'",
            "Отдел as \'Отдел\'",
            "Оклад as \'Оклад\'",
            "Тел as \'Тел\'"})]
    public class Сотрудник : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private string fДолжность;
        
        private string fОтдел;
        
        private int fОклад;
        
        private string fТел;
        
        // *** Start programmer edit section *** (Сотрудник CustomMembers)

        // *** End programmer edit section *** (Сотрудник CustomMembers)

        
        /// <summary>
        /// Должность.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Должность CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Должность CustomAttributes)
        [StrLen(255)]
        public virtual string Должность
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Должность Get start)

                // *** End programmer edit section *** (Сотрудник.Должность Get start)
                string result = this.fДолжность;
                // *** Start programmer edit section *** (Сотрудник.Должность Get end)

                // *** End programmer edit section *** (Сотрудник.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Должность Set start)

                // *** End programmer edit section *** (Сотрудник.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (Сотрудник.Должность Set end)

                // *** End programmer edit section *** (Сотрудник.Должность Set end)
            }
        }
        
        /// <summary>
        /// Оклад.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Оклад CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Оклад CustomAttributes)
        public virtual int Оклад
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Оклад Get start)

                // *** End programmer edit section *** (Сотрудник.Оклад Get start)
                int result = this.fОклад;
                // *** Start programmer edit section *** (Сотрудник.Оклад Get end)

                // *** End programmer edit section *** (Сотрудник.Оклад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Оклад Set start)

                // *** End programmer edit section *** (Сотрудник.Оклад Set start)
                this.fОклад = value;
                // *** Start programmer edit section *** (Сотрудник.Оклад Set end)

                // *** End programmer edit section *** (Сотрудник.Оклад Set end)
            }
        }
        
        /// <summary>
        /// Отдел.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Отдел CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Отдел CustomAttributes)
        [StrLen(255)]
        public virtual string Отдел
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Отдел Get start)

                // *** End programmer edit section *** (Сотрудник.Отдел Get start)
                string result = this.fОтдел;
                // *** Start programmer edit section *** (Сотрудник.Отдел Get end)

                // *** End programmer edit section *** (Сотрудник.Отдел Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Отдел Set start)

                // *** End programmer edit section *** (Сотрудник.Отдел Set start)
                this.fОтдел = value;
                // *** Start programmer edit section *** (Сотрудник.Отдел Set end)

                // *** End programmer edit section *** (Сотрудник.Отдел Set end)
            }
        }
        
        /// <summary>
        /// Тел.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Тел CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Тел CustomAttributes)
        [StrLen(255)]
        public virtual string Тел
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Тел Get start)

                // *** End programmer edit section *** (Сотрудник.Тел Get start)
                string result = this.fТел;
                // *** Start programmer edit section *** (Сотрудник.Тел Get end)

                // *** End programmer edit section *** (Сотрудник.Тел Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Тел Set start)

                // *** End programmer edit section *** (Сотрудник.Тел Set start)
                this.fТел = value;
                // *** Start programmer edit section *** (Сотрудник.Тел Set end)

                // *** End programmer edit section *** (Сотрудник.Тел Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.ФИО CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.ФИО Get start)

                // *** End programmer edit section *** (Сотрудник.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Сотрудник.ФИО Get end)

                // *** End programmer edit section *** (Сотрудник.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.ФИО Set start)

                // *** End programmer edit section *** (Сотрудник.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Сотрудник.ФИО Set end)

                // *** End programmer edit section *** (Сотрудник.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникE", typeof(IIS.Proektirovanie_.Сотрудник));
                }
            }
            
            /// <summary>
            /// "СотрудникL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникL", typeof(IIS.Proektirovanie_.Сотрудник));
                }
            }
        }
    }
}
